server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        # Utilize aspas simples para o asterisco no YAML
        include: 'prometheus,health,metrics'
  endpoint:
    # Prometheus vem habilitado por padrão se a dependência estiver presente,
    # mas você pode forçar aqui
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true



