apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-nginx
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-stack
  template:
    metadata:
      labels:
        app: prometheus-stack
    spec:
      volumes:
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: "/"
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus
