apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring # ajuste conforme seu namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi # ajuste o tamanho necessário
  # storageClassName: standard # opcional: defina sua SC
